package net.ade.texturesmod.common.regisrtyitem;

import net.ade.texturesmod.ModMain;
import net.ade.texturesmod.itemgroup.NewGroup;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

/**
 * @author lhy
 */
public class ItemInit {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, ModMain.MODID);

    public static final RegistryObject<Item> A1 =
            ITEMS.register("a1", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A2 =
            ITEMS.register("a2", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A3 =
            ITEMS.register("a3", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A4 =
            ITEMS.register("a4", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A5 =
            ITEMS.register("a5", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A6 =
            ITEMS.register("a6", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A7 =
            ITEMS.register("a7", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A8 =
            ITEMS.register("a8", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A9 =
            ITEMS.register("a9", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A10 =
            ITEMS.register("a10", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A11 =
            ITEMS.register("a11", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A12 =
            ITEMS.register("a12", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A13 =
            ITEMS.register("a13", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A14 =
            ITEMS.register("a14", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A15 =
            ITEMS.register("a15", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A16 =
            ITEMS.register("a16", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A17 =
            ITEMS.register("a17", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A18 =
            ITEMS.register("a18", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A19 =
            ITEMS.register("a19", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A20 =
            ITEMS.register("a20", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A21 =
            ITEMS.register("a21", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A22 =
            ITEMS.register("a22", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A23 =
            ITEMS.register("a23", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A24 =
            ITEMS.register("a24", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A25 =
            ITEMS.register("a25", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A26 =
            ITEMS.register("a26", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A27 =
            ITEMS.register("a27", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A28 =
            ITEMS.register("a28", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A29 =
            ITEMS.register("a29", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A30 =
            ITEMS.register("a30", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A31 =
            ITEMS.register("a31", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A32 =
            ITEMS.register("a32", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A33 =
            ITEMS.register("a33", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A34 =
            ITEMS.register("a34", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A35 =
            ITEMS.register("a35", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A36 =
            ITEMS.register("a36", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A37 =
            ITEMS.register("a37", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A38 =
            ITEMS.register("a38", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A39 =
            ITEMS.register("a39", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A40 =
            ITEMS.register("a40", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A41 =
            ITEMS.register("a41", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A42 =
            ITEMS.register("a42", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A43 =
            ITEMS.register("a43", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A44 =
            ITEMS.register("a44", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A45 =
            ITEMS.register("a45", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A46 =
            ITEMS.register("a46", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A47 =
            ITEMS.register("a47", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> a48 =
            ITEMS.register("a48", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A49 =
            ITEMS.register("a49", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A50 =
            ITEMS.register("a50", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A51 =
            ITEMS.register("a51", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A52 =
            ITEMS.register("a52", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A53 =
            ITEMS.register("a53", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A54 =
            ITEMS.register("a54", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A55 =
            ITEMS.register("a55", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A56 =
            ITEMS.register("a56", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A57 =
            ITEMS.register("a57", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A58 =
            ITEMS.register("a58", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A59 =
            ITEMS.register("a59", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A60 =
            ITEMS.register("a60", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A61 =
            ITEMS.register("a61", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A62 =
            ITEMS.register("a62", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A63 =
            ITEMS.register("a63", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A64 =
            ITEMS.register("a64", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A65 =
            ITEMS.register("a65", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A66 =
            ITEMS.register("a66", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A67 =
            ITEMS.register("a67", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A68 =
            ITEMS.register("a68", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A69 =
            ITEMS.register("a69", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A70 =
            ITEMS.register("a70", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A71 =
            ITEMS.register("a71", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A72 =
            ITEMS.register("a72", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A73 =
            ITEMS.register("a73", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A74 =
            ITEMS.register("a74", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A75 =
            ITEMS.register("a75", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A76 =
            ITEMS.register("a76", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A77 =
            ITEMS.register("a77", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A78 =
            ITEMS.register("a78", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A79 =
            ITEMS.register("a79", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A80 =
            ITEMS.register("a80", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A81 =
            ITEMS.register("a81", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A82 =
            ITEMS.register("a82", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A83 =
            ITEMS.register("a83", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A84 =
            ITEMS.register("a84", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A85 =
            ITEMS.register("a85", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A86 =
            ITEMS.register("a86", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A87 =
            ITEMS.register("a87", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A88 =
            ITEMS.register("a88", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A89 =
            ITEMS.register("a89", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A90 =
            ITEMS.register("a90", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A91 =
            ITEMS.register("a91", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A92 =
            ITEMS.register("a92", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A93 =
            ITEMS.register("a93", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A94 =
            ITEMS.register("a94", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A95 =
            ITEMS.register("a95", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A96 =
            ITEMS.register("a96", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A97 =
            ITEMS.register("a97", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A98 =
            ITEMS.register("a98", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A99 =
            ITEMS.register("a99", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A100 =
            ITEMS.register("a100", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A101 =
            ITEMS.register("a101", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A102 =
            ITEMS.register("a102", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A103 =
            ITEMS.register("a103", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A104 =
            ITEMS.register("a104", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A105 =
            ITEMS.register("a105", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A106 =
            ITEMS.register("a106", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A107 =
            ITEMS.register("a107", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> a108 =
            ITEMS.register("a108", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A109 =
            ITEMS.register("a109", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A110 =
            ITEMS.register("a110", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A111 =
            ITEMS.register("a111", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A112 =
            ITEMS.register("a112", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A113 =
            ITEMS.register("a113", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A114 =
            ITEMS.register("a114", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A115 =
            ITEMS.register("a115", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A116 =
            ITEMS.register("a116", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A117 =
            ITEMS.register("a117", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A118 =
            ITEMS.register("a118", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A119 =
            ITEMS.register("a119", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A120 =
            ITEMS.register("a120", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A121 =
            ITEMS.register("a121", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A122 =
            ITEMS.register("a122", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A123 =
            ITEMS.register("a123", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A124 =
            ITEMS.register("a124", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A125 =
            ITEMS.register("a125", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A126 =
            ITEMS.register("a126", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A127 =
            ITEMS.register("a127", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A128 =
            ITEMS.register("a128", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> a129 =
            ITEMS.register("a129", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A130 =
            ITEMS.register("a130", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A131 =
            ITEMS.register("a131", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A132 =
            ITEMS.register("a132", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A133 =
            ITEMS.register("a133", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A134 =
            ITEMS.register("a134", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A135 =
            ITEMS.register("a135", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A136 =
            ITEMS.register("a136", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A137 =
            ITEMS.register("a137", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A138 =
            ITEMS.register("a138", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A139 =
            ITEMS.register("a139", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A140 =
            ITEMS.register("a140", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A141 =
            ITEMS.register("a141", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A142 =
            ITEMS.register("a142", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A143 =
            ITEMS.register("a143", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
    public static final RegistryObject<Item> A144 =
            ITEMS.register("a144", () -> new Item(new Item.Properties().group(NewGroup.newGroup)));
}
